apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jhml3mhfy-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-9fea656d3e.3140.p3.openshiftapps.com/rhtap/rhtap-qe:d2bf686c10026ad13bbc9c7bdd96e9ff8b10730f@sha256:e8b0679890100e041f431e442d85e82036766d4105051e6adf2e6cc31423f26e
          name: container-image
